### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by hakutzu** [aso14/DTelegram#10]
### Discussed in https://github.com/Bunker-x/DTelegram/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **hakutzu** October 16, 2024</sup>
I'd like to host a bot but it doesn't seem to be working for me.
[code]

Traceback (most recent call last):
  File "/home/haku/link-media-scraper-bot/bot.py", line 17, in <module>
    app = session.session_gen.gen_session()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/haku/link-media-scraper-bot/session/session_gen.py", line 10, in gen_session
    with app:
  File "/home/haku/link-media-scraper-bot/env/lib/python3.11/site-packages/pyrogram/client.py", line 280, in __enter__
    return self.start()
           ^^^^^^^^^^^^
  File "/home/haku/link-media-scraper-bot/env/lib/python3.11/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/haku/link-media-scraper-bot/env/lib/python3.11/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/haku/link-media-scraper-bot/env/lib/python3.11/site-packages/pyrogram/methods/auth/connect.py", line 47, in connect
    await self.session.start()
  File "/home/haku/link-media-scraper-bot/env/lib/python3.11/site-packages/pyrogram/session/session.py", line 142, in start
    raise e
  File "/home/haku/link-media-scraper-bot/env/lib/python3.11/site-packages/pyrogram/session/session.py", line 109, in start
    await self.send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
  File "/home/haku/link-media-scraper-bot/env/lib/python3.11/site-packages/pyrogram/session/session.py", line 333, in send
    raise BadMsgNotification(result.error_code)
pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.

[/code]</div>

**Comment by aso14** [comment]
Hi guy ! is Delphi library ?
